all:
  hosts:
    vm1:
      ansible_host: 192.168.25.10
      ansible_user: vagrant
    #vm2:
    #  ansible_host: 192.168.25.11
    #  ansible_user: vagrant
    #vm3:
    #  ansible_host: 192.168.25.12
    #  ansible_user: vagrant