---
- name: Create containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Generate containerd conf
  ansible.builtin.shell:
    cmd: containerd config default > /etc/containerd/config.toml
    creates: /etc/containerd/config.toml

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: yes