---
- name: Update, upgrade and install packages
  ansible.builtin.apt:
    name:
      - containerd
      - apt-transport-https
      - ca-certificates
      - gpg
    update_cache: yes

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and add Kubernetes apt key
  ansible.builtin.shell:
    cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  copy:
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Update, upgrade and install packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- name: Hold kubelet, kubeadm and kubectl 
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  
- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started