---
- name: Check if swap is in /etc/fstab
  shell: grep -q "swap" /etc/fstab
  register: swap_in_fstab
  changed_when: false
  failed_when: false

- name: Disable SWAP
  shell: |
    swapoff -a

- name: Remove SWAP 
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: swap_in_fstab.rc == 0

- name: Upload containerd conf
  ansible.builtin.copy:
    src: files/containerd.conf
    dest: /etc/modules-load.d/containerd.conf

- name: Load overlay kernel module
  community.general.modprobe:
    name: overlay
    state: present

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Upload k8s conf
  ansible.builtin.copy:
    src: files/99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system